apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backup-pvc
spec:
  accessModes:
    - {{ .Values.backup.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backup.storage }}
