apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: mysql
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mysql
