apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devops-web
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-devops-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devops-web
    spec:
      containers:
      - name: devops-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-devops-web-config
              key: API_HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-devops-web-config
              key: PORT
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
