apiVersion: v1
kind: Service
metadata:
  name: devops-api
spec:
  selector:
    app: {{ .Release.Name }}-devops-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
